PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>
PREFIX steyn: <http://steynlab.ahri.org/identifiers/>
PREFIX redcap:<http://steynlab.ahri.org/redcap/>
PREFIX ahri:  <https://population.ahri.org/api/>
PREFIX ome:   <http://www.openmicroscopy.org/rdf/2016-06/ome_core/>
PREFIX dcterms:<http://purl.org/dc/terms/>

SELECT DISTINCT
  ?organ
  ?slnum
  ?redcap
  ?omero_project
  ?age
  ?specimen_source
  ?cause_of_death
  (GROUP_CONCAT(?image; separator=",") AS ?images)
  #(GROUP_CONCAT(?image_name; separator=",") AS ?image_names)
WHERE {
  VALUES ?specimen_source {"5"}  # restrict to IALCH Forensic Pathology

  # REDCap record
  ?redcap ahri:uri ?uri ;
          ahri:age_main ?age ;
          ahri:specimen_source ?specimen_source ;
          ahri:cause_of_death ?cause_of_death ;
          ahri:organ_collected ?organ .

  # Link via same AHRI URI into OMERO
  ?omeRecord ome:uri ?uri .
  ?omero_project dcterms:hasPart ?omeRecord .

  # Navigate to datasets/images
  ?omero_project dcterms:hasPart ?omero_dataset .
  ?omero_dataset dcterms:hasPart ?image .
  #?image rdfs:label ?image_name .

  # Extract SL number from URI
  BIND(REPLACE(STR(?uri), "^https://population\\.ahri\\.org/api/", "") AS ?slnum)
}
GROUP BY ?slnum ?redcap ?omero_project ?age ?specimen_source ?cause_of_death ?organ
